--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "SYSTEM"."ROLES_DE_USUARIO" DROP CONSTRAINT "FK_USERNAME";

ALTER TABLE "SYSTEM"."USUARIOS" DROP CONSTRAINT "SYS_C007114";

ALTER TABLE "SYSTEM"."ROLES_DE_USUARIO" DROP CONSTRAINT "SYS_C007126";

DROP INDEX "SYSTEM"."SYS_C007114";

DROP INDEX "SYSTEM"."ROLES_DE_USUARIO_ID";

DROP INDEX "SYSTEM"."SYS_C007126";

DROP TABLE "SYSTEM"."USUARIOS";

DROP TABLE "SYSTEM"."ROLES_DE_USUARIO";

CREATE TABLE "SYSTEM"."USUARIOS" (
		"USUARIO" VARCHAR2(45) NOT NULL,
		"CONTRASENA" VARCHAR2(60) NOT NULL,
		"VALIDO" NUMBER(1 , 0) DEFAULT 0   NOT NULL
	);

CREATE TABLE "SYSTEM"."ROLES_DE_USUARIO" (
		"ID_ROL_DE_USUARIO" NUMBER NOT NULL,
		"USUARIO" VARCHAR2(45) NOT NULL,
		"ROLE" VARCHAR2(45) NOT NULL
	);

CREATE UNIQUE INDEX "SYSTEM"."SYS_C007114" ON "SYSTEM"."USUARIOS" ("USUARIO" ASC);

CREATE UNIQUE INDEX "SYSTEM"."ROLES_DE_USUARIO_ID" ON "SYSTEM"."ROLES_DE_USUARIO" ("USUARIO" ASC, "ROLE" ASC);

CREATE UNIQUE INDEX "SYSTEM"."SYS_C007126" ON "SYSTEM"."ROLES_DE_USUARIO" ("ID_ROL_DE_USUARIO" ASC);

ALTER TABLE "SYSTEM"."USUARIOS" ADD CONSTRAINT "SYS_C007114" PRIMARY KEY ("USUARIO");

ALTER TABLE "SYSTEM"."ROLES_DE_USUARIO" ADD CONSTRAINT "SYS_C007126" PRIMARY KEY ("ID_ROL_DE_USUARIO");

ALTER TABLE "SYSTEM"."ROLES_DE_USUARIO" ADD CONSTRAINT "FK_USERNAME" FOREIGN KEY ("USUARIO")
	REFERENCES "SYSTEM"."USUARIOS" ("USUARIO")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

