//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.05 at 09:44:33 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/company/servicioweb/servicioLogeo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.company.servicioweb.serviciologeo;
